name: CI
on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

jobs:
  build-linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: "actions/checkout@v3"
      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'debian-latest'
        run: |
          sudo apt-get update
          sudo apt-get -y install libsdl1.2-dev
      - name: Build
        run: |
          make
